#!/bin/sh

passes=~/term/new/build/deb/pass/
llvmtools=~/term/llvm/build/Release+Asserts/bin/
llvmgcc=~/term/llvm-gcc-bin/bin/

llvmgcc=$llvmgcc"x86_64-unknown-linux-gnu-llvm-g++"
llvmopt=$llvmtools"opt"
llvmas=$llvmtools"llvm-as"

echo "[1:$1]Generating llvm source"
$llvmgcc -O2 -S -emit-llvm $1.cpp
echo "[2:$1]Assembling llvm source to bytecode"
$llvmas $1.s -f
echo "[3:$1]Swinging through functions, greetings"
$llvmopt -load $passes"libhelloWorld.so" -hello < $1.s.bc > /dev/null
   
